# Generated by Django 4.1.2 on 2022-10-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_track_options_rename_img_track_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
    ]
