# Generated by Django 4.1.2 on 2022-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tracks', models.ManyToManyField(to='main_app.track')),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
