# Generated by Django 4.1.2 on 2022-10-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main_app.artist'),
        ),
    ]
