# Generated by Django 4.1.2 on 2022-10-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_playlist_delete_artist'),
        ('main_app', '0005_rename_img_artist_image_alter_track_artist'),
    ]

    operations = [
    ]
